trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: config.properties
  - name: CredFileLibrary
    value: product-readiness.omf_api_java.ocs.properties
  - name: CredFileLibraryOP
    value: product-readiness.omf_api_java.onprem.properties
  - name: analysisProject
    value: OMF_API_Java

jobs:
  - job: Tests_OCS
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Linux
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
          goals: 'test'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Run tests'

  - job: Tests_OnPrem
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryOP)

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
          goals: 'test'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Run tests'

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
          goals: 'package'
          options: '-DskipTests'
        displayName: 'Build'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
